### ISSUE TITLE
Global Content Repository site is always created even if the feature is disabled

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-core#572] opened 2022-09-07 09:22 UTC
Steps to reproduce:
1. Disable the global media library via `global-media-library: false` in composer.json
2. Run `composer server cli -- altis migrate` to upgrade from a version prior to v9
3. Observe that the global media library site is still created even though it's not needed and won't be used

**Comment by rmccue** [comment] 2022-09-07 10:58
The global content repository is not just for the media library, but is intentionally created for other central purposes we may want, so this isn't a bug.

Is there any specific reason you don't want the site created?

**Comment by johnbillion** [comment] 2022-09-07 11:01
This was on a client that only has one site on their network, and most likely will only ever have one, so the extra site seems unnecessary.

**Comment by rmccue** [comment] 2022-09-07 11:32
Both the architectural choice to use multisite as well as the creation of the global content repository are designed to be future proofing for if they do decide to have more sites in the future, so if it's not getting in the way of anything, then the feature's working as intended. Closing this one out, but if there's any tangible problems this creates, happy to look at ways to mitigate it.

**Closed by rmccue** 2022-09-07 11:32 UTC
