### ISSUE TITLE
Telemetry is sent in automated testing

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-core#472] opened 2022-05-20 17:07 UTC
Currently I believe there's nothing to stop telemetry data being sent to Segment in automated testing. Because those automated tests will typically use a fresh DB on run, with new users, we are blowing past our MTUs in Segment, costing us a lot.

We should probably at least detect if the `php_sapi_name()` is CLI, or alternatively only fire Telemetry on web-requests (by looking for $_SERVER headers etc).

**Comment by roborourke** [comment] 2022-05-26 13:51
Duplicate of https://github.com/humanmade/product-dev/issues/1046

CLI might be useful to exclude if we're concerned about things like imports/ exports too but there may be useful info from CLI runs too.

**Closed by roborourke** 2022-05-26 13:51 UTC
Labels: bug

**Comment by joehoyle** [comment] 2022-05-27 07:53
Yeah I don't think we'd want to run it on import, that would cost us a lot too. Segment pricing and the way we current track the amount of users right now (based of save post) I don't think we can do anything other than collect data on real-user activity
