### ISSUE TITLE
Updating Altis requires two calls to `composer update`

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-core#119] opened 2021-01-07 12:43 UTC
Updating Altis requires running `composer update` twice, due to our use of the installer location overrides and the load order of Composer plugins. This subverts user expectations, and often leads to fatal errors which aren't necessarily caught.

Steps to reproduce:
1. Install Altis v4
2. Upgrade to Altis v5 using `composer update`
3. Observe `humanmade/post-cloner` is installed to the wrong location
4. Run `composer update` again
5. Observe `humanmade/post-cloner` is installed to the right location

(Repeat for any major versions as required)

Users should not need to install twice, and files should be placed into the right location after running `composer update` once.

Acceptance criteria:

- [ ] ...

**Comment by rmccue** [comment] 2021-01-07 13:02
This is due to the hardcoded list in the installer. The plugin is loaded in at the start (as v4), and then not reloaded for v5, so the list of overridden paths isn't updated.

We should be able to fix this by pulling the paths from the Composer package manager instead; Composer must have the new packages in memory already, so we can pull from there. In addition, we might be able to move these out of altis/core and into the actual packages that require them instead.

**Comment by stuartshields** [comment] 2021-01-14 06:19
@rmccue How do we get around this when deploying for the first time to dev/staging/production? I remember seeing this happen on dev and had to redeploy, but when it comes to production I don't think we can do that.

**Comment by ntwb** [comment] 2021-01-14 08:22
@stuartshields Yesterday I expected the above to be an issue with a production deployment on SC RB

To workaround this in advance after the pr was merged and Vantage had “built” the commit I forced a rebuild of that commit, once the second build had completed the second time I confirmed the changes I expected to see from the build logs and then I clicked “deploy” and everything worked as expected

**Comment by ivankristianto** [comment] 2021-01-14 08:24
Today I experience a deployment incident on NR due to the lock file need to get cleared. There is a missing package and cause error 5xx. Clearing the lock and cache manually, then do force rebuild fixed it.

**Comment by rmccue** [comment] 2021-01-14 11:35
Clearing the build cache *before* deploying will also ensure this error does not occur.

**Closed** 2021-02-01 09:43 UTC
Labels: bug
